name: relay_sdk
description: Official Dart/Flutter SDK for the Relay API.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  dio: ^5.4.3+1
  web_socket_channel: ^2.4.5
  json_annotation: ^4.9.0

dev_dependencies:
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  test: ^1.25.0
  mocktail: ^1.0.4
